### ISSUE TITLE
error in TIMEDB Deconv quanTIseq

### ISSUE THREAD

**Issue by Jyoung-0108** [deepomicslab/TIMEDB#4]
hello, when I using the TIMEDB Deconv quanTIseq for analysis, I encountered an error. My upload file format seems to go wrong. But I tried to download the demo file provided by TIMEDB and upload it for analysis, it also report the same error which is 'Error in file(file, "rt") : cannot open the connection'
and the full Error Message is 
To execute GATK run: java -jar $EBROOTGATK/GenomeAnalysisTK.jar

The following have been reloaded with a version change:
  1) ncdf4/1.17-r-3.6.3 => ncdf4/1.17-r-4.0.0
  2) r-bundle-bioconductor/3.10-r-3.6.3 => r-bundle-bioconductor/3.11-r-4.0.0
  3) r/3.6.3 => r/4.0.0

Loading required package: stringr
Loading required package: optparse
Loading required package: dplyr

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Loading required package: limma
Loading required package: immunedeconv
Loading required package: EPIC
Loading required package: EnrichmentBrowser
Loading required package: SummarizedExperiment
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:parallel':

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following object is masked from 'package:limma':

    plotMA

The following objects are masked from 'package:dplyr':

    combine, intersect, setdiff, union

The following objects are masked from 'package:stats':

    IQR, mad, sd, var, xtabs

The following objects are masked from 'package:base':

    Filter, Find, Map, Position, Reduce, anyDuplicated, append,
    as.data.frame, basename, cbind, colnames, dirname, do.call,
    duplicated, eval, evalq, get, grep, grepl, intersect, is.unsorted,
    lapply, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
    pmin.int, rank, rbind, rownames, sapply, setdiff, sort, table,
    tapply, union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors

Attaching package: 'S4Vectors'

The following objects are masked from 'package:dplyr':

    first, rename

The following object is masked from 'package:base':

    expand.grid

Loading required package: IRanges

Attaching package: 'IRanges'

The following objects are masked from 'package:dplyr':

    collapse, desc, slice

Loading required package: GenomeInfoDb
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: DelayedArray
Loading required package: matrixStats

Attaching package: 'matrixStats'

The following objects are masked from 'package:Biobase':

    anyMissing, rowMedians

The following object is masked from 'package:dplyr':

    count

Attaching package: 'DelayedArray'

The following objects are masked from 'package:matrixStats':

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following objects are masked from 'package:base':

    aperm, apply, rowsum

Loading required package: graph

Attaching package: 'graph'

The following object is masked from 'package:stringr':

    boundary

Attaching package: 'EnrichmentBrowser'

The following object is masked from 'package:BiocGenerics':

    normalize

Loading required package: ConsensusTME
Loading required package: MASS

Attaching package: 'MASS'

The following object is masked from 'package:dplyr':

    select

Loading required package: preprocessCore
Error in file(file, "rt") : cannot open the connection
Calls: run -> read.csv -> read.table -> file
In addition: Warning messages:
1: In file(file, "rt") :
  'raw = FALSE' but '/' is not a regular file
2: In file(file, "rt") :
  cannot open file '/': it is a directory
Execution halted

Script failed. Exit code: 1

thanks a lot for your help.

**Comment by kristaxying** [comment]
Hello, thanks for your response. I have tested the demo file and can confirm that it can be submitted successfully. Below is the picture depicting the parameters I used.
![quantiseq](https://github.com/deepomicslab/TIMEDB/assets/112065199/b5c18f80-bfd1-49be-b714-343e4a8e032e)

You may try again and if you encounter any further issues, please don't hesitate to reach out.
We will assist you.
